# Site settings and SEO
title: Hello World\s
author: Pery Mimon
tagline: A personal playground and technical blog.
description:
  A space to share my discoveries and explorations in JS, CSS, and HTML.
  Most of this technical blog is built from scratch — no compilers, minimal tools.
twitter:
  username: PMimon70549
  card: summary
logo: /assets/grow-avatar-2.png

defaults:
  - scope:
      path: ""
    values:
      image:  /assets/grow-avatar-2.png

google_site_verification: E0AhPdfyI3x5dt5vuR0ZoDwhcX-Ba0g02-FdBYMqtjs

future: true
excerpt_separator: <!--more-->
# Specify locations for layout, includes, data relative to the root
includes_dir: admin/_includes
layouts_dir:  admin/_layouts
data_dir:     admin/_data

# GitHub Pages specific settings
baseurl: /portfolio # Matches repository name
url: https://perymimon.github.io # Main GitHub Pages URL
theme: null

# Build settings
markdown: kramdown # Standard Markdown processor for Jekyll
highlighter: nil
## More Collection
collections_dir: contents
collections:
  authors:
    output: true
    permalink: contents/authors/:name
  posts:
    output: true
    permalink: contents/post/:slug

# RSS configs
feed:
  path: feed.xml
  posts_limit: 10
  excerpt_only: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# Ensure Jekyll includes the 'contents/assets' folder in the build output
#include:
#  - "contents/assets"
  # Add other top-level files/folders from the root you might need copied that start with _ or .
  # - "_redirects"
# Optional: Add default layout for posts later if you want
# defaults:
#   - scope:
#       path: "_posts"
#       type: "posts"
#     values:
#       layout: "post"