local_backend: true

backend:
  name: github
  repo: perymimon/portfolio
  branch: main
  base_url: https://decap-proxy.pery-mimon.workers.dev
  auth_endpoint: auth
#  auth: { token: "" }
#  base_url: https://perymimon.github.io
#  auth_endpoint: portfolio
#  base_url: http://localhost:63341
#  auth_endpoint: /radu-stuff/admin/oauth.html




publish_mode: simple

# Media folder where uploads will be stored
media_folder: "contents/uploads"

# Collections define the structure for content types
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Tech Post" # Used in the UI
    folder: "contents/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]"
        picker_utc: true
        default: "{{now}}"
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      -  label: 'Author'
         name: 'author'
         widget: 'relation'
         collection: 'authors'
         display_fields: [ display_name ]
         search_fields: [ display_name ]
         value_field: 'name'
         default: pery
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'authors'
    label: 'Authors'
    folder: 'contents/_authors'
    create: true
    editor:
      preview: false
    slug: "{{name}}"
    fields:
      - { label: 'Avatar', name: 'avatar', widget: 'image', required: true }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
