local_backend: true
site_url: https://perymimon.github.io/portfolio/
show_preview_links: true
search: true

backend:
  name: github
  repo: perymimon/portfolio
  branch: main
  base_url: https://decap-proxy.pery-mimon.workers.dev
  auth_endpoint: auth
#  base_url: https://perymimon.github.io
#  auth_endpoint: portfolio
#  base_url: http://localhost:63341
#  auth_endpoint: /radu-stuff/admin/oauth.html

publish_mode: editorial_workflow

# Media folder where uploads will be stored
media_folder: "admin/uploads"

collections:
  # Posts collection
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Tech Post" # Used in the UI
    folder: "admin/collections/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }

      - label: Publish Date
        name: date
        widget: datetime
        format: YYYY-MM-DDTHH:mm:ss[Z]
        picker_utc: true
        required: true

      - { label: "Featured Image", name: "image", widget: "image", required: false }

      - widget: relation
        label: Author
        name: author
        default: pery
        value_field: name
        collection: authors
        display_fields: [ display_name ]
        search_fields: [ display_name ]

      - label: Body
        name: body
        widget: markdown

      - label: Tags
        name: tags
        widget: string

      - label: html
        name: code_html
        widget: code
        default_language: html
        allow_language_selection: false
        output_code_only: true
        required: false

      - label: css
        name: code_css
        widget: code
        default_language: css
        allow_language_selection: false
        output_code_only: true
        required: false

      - label: js
        name: code_js
        widget: code
        default_language: javascript
        allow_language_selection: false
        output_code_only: true
        required: false

  # Authors collection
  - name: 'authors'
    label: 'Authors'
    folder: 'admin/collections/_authors'
    create: true
    editor:
      preview: false
    slug: "{{name}}"
    fields:
      - { label: 'Avatar', name: 'avatar', widget: 'image', required: true }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }




